name: history
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+10

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8


  get: ^4.7.2
  lottie: ^3.3.2
  get_storage: ^2.1.1
  disposable_cached_images: ^1.2.1
  flutter_screenutil: ^5.9.3
  auth_buttons: ^3.0.3
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  snow_fall_animation: ^0.0.1+3
  flutter_svg: ^2.0.16
  fluentui_system_icons: ^1.1.270
  pull_to_refresh: ^2.0.0
  flutter_tabler_icons: ^1.43.0
  path_provider: ^2.1.5
  flutter_downloader: ^1.11.8
  permission_handler: ^12.0.1
  dio: ^5.7.0
  flutter_pdfview: ^1.4.0
  skeletonizer: ^2.0.1
  flutter_html: ^3.0.0
  easy_docs_viewer: ^0.0.2-unstable-release
  #launcher_name: ^1.0.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_core_platform_interface: ^6.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  launcher_name: ^1.0.2

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/science.json
    - assets/lottie/book.json
    - assets/lottie/settings.json
    - assets/images/
    - assets/icons/


launcher_name:
  default: "O‘zbekiston tarixi va Huquqshunoslik"
  ru: "История Узбекистана и Правоведение"
  uz: "O‘zbekiston tarixi va Huquqshunoslik"